default: &default
  adapter: postgresql
  host: localhost
  encoding: utf8
  username: postgres 
  password: devsinc
  pool: 5
  port: 5432
  timeout: 5000

development:
  <<: *default
  database: Bike_development

test:
  <<: *default
  database: Bike_test

production:
  <<: *default
  database: Bike_production
  username: <%= ENV['BIKE_DATABASE_USERNAME'] %>
  password: <%= ENV['BIKE_DATABASE_PASSWORD'] %>
